# Generated by Django 5.0.6 on 2024-06-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_project_technologies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='skill',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
